# Generated by Django 3.1.5 on 2021-03-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demomodal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
